### PR TITLE
fixed clean-css to a specific version in app-setup.js

### PR DESCRIPTION
**Pull request by guptavaibhav18197**
In clean-css 4.0(+) API and CLI interfaces are split, so API stays in this repository while CLI moves to clean-css-cli, also its not compatible with the flag --root(used while flask assets build). I could have added clean-css-cli separately but for compatibility issue with flags like --root its best to pin to css previous version.

### CODE REVIEW

**Comment by lnielsen** [comment]
Thanks for the PR. To fix the build error you probably need to update Flask-WTF from 0.13 to 0.13.1 in https://github.com/inveniosoftware/invenio-userprofiles/blob/master/setup.py#L84

**Comment by guptavaibhav18197** [comment]
Sir, I only changed the clean-css version and then tested it completely again. It did away with all the errors!.
So I am not sure that why should we change flask-WTF version!

**Comment by krzysztof** [comment]
@guptavaibhav18197 
Travis is failing on first several because of the old version of Flask-WTF here: https://travis-ci.org/inveniosoftware/invenio-userprofiles/builds/210730083

It's not related to your code, it's just that userprofile master branch is also failing at the moment.

**Comment by lnielsen** [comment]
Thanks for PR

**Pull request merged**
